version: '3'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graph
      MYSQL_PASSWORD: root
    volumes:
      - database-volume:/var/lib/mysql
    
volumes:
  database-volume:
    external: false